apiVersion: v1
kind: Secret
metadata:
  name: azure-msal-service-secret
type: Opaque
data:
  client-id: {{ .Values.clientId | b64enc | quote }}
  client-secret: {{ .Values.clientSecret | b64enc | quote }}
  tenant-id: {{ .Values.tenantId | b64enc | quote }}
