# kubectl delete -A ValidatingWebhookConfiguration ingress-ingress-nginx-admission
networking:
  sftp_port: 22
metallb:
  enabled: false
ingress-nginx:
  controller:
    replicaCount: 3
    service:
      enabled: false
    serviceAccount:
      create: true
      name: nginx-ingress-serviceaccount
    rbac:
      create: true
      scope: namespaced
    clusterRole:
      create: true
      name: "{{ .Release.Name }}-{{ .Release.Namespace }}-ingress-nginx"
    labels:
      app: nginx-ingress-controller
    podLabels:
      app: nginx-ingress-controller

# Primary API Load Balancer
primary_api:
  createLoadBalancer: false
  advertiseL2MetalLb: false
  ip: "192.168.123.205"
  port: 80
  https_port: 443

# Secondary API Load Balancer
secondary_api:
  createLoadBalancer: false
  advertiseL2MetalLb: false
  ip: "192.168.123.206"
  port: 80
  https_port: 443

# Admin API Load Balancer
admin_api:
  createLoadBalancer: true
  advertiseL2MetalLb: false
  ip: "192.168.123.207"
  port: 80
  https_port: 443

