apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-api-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/load-balance: "round_robin"
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.primary_hostname }}
      http:
        paths:
        - path: /api/policy
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-primary-api-external
              port:
                number: {{ .Values.networking.api_port }}
    - host: {{ .Values.secondary_hostname }}
      http:
        paths:
        - path: /api/policy
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-secondary-api-external
              port:
                number: {{ .Values.networking.api_port }}

