# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: cdr-pv-volume
#   labels:
#     type: local
#   annotations:
#     pv.beta.kubernetes.io/gid: "1001"
# spec:
#   storageClassName: hostpath
#   capacity:
#     storage: 10Gi
#   accessModes:
#     - ReadWriteOnce
#   hostPath:
#     path: sftp