# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: cdr-pv-claim
# spec:
#   storageClassName: hostpath
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 3Gi