dependencies:
  - name: postgresql
    version: 9.1.1
    repository: https://charts.bitnami.com/bitnami
  # - name: prometheus
    # version: 13.3.2
    # repository: https://prometheus-community.github.io/helm-charts
  # - name: grafana
    # version: 6.3.0
    # repository: https://grafana.github.io/helm-charts
# {{- if .Values.use_metal_lb }}
#   - name: metallb
#     version: 2.3.0
#     repository: https://charts.bitnami.com/bitnami
# {{- end }}
