apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: admin-service-http
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-admin-internal-service
                port:
                  number: 4000
          # - path: /
          #   pathType: Prefix
          #   backend:
          #     service:
          #       name: vue-service
          #       port:
          #         number: 80
