{{- if and .Values.secondary_api.createLoadBalancer .Values.secondary_api.advertiseL2MetalLb }}
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: secondary-ip
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - {{ .Values.secondary_api.ip }}/32
  autoAssign: false
status: {}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: secondary-l2-advert
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - secondary-ip
{{- end }}
