hostname:
image: calltelemetry/web:0.4.1
  # repository: calltelemetry/web
  # tag: 0.4.1
resources: {}
metallb:
  existingConfigMap: metallb-config
  speaker:
    secretKey: metallb-secretkey
# traefik:
  # service.annotations."metallb\.universe\.tf\/address-pool": default
web:
  cpus: 1
  imagePullPolicy: Always
  replicas: 1
cdr_root_path: "/home/app/sftp"
db_name: calltelemetry_prod
db_hostname: ctsql.pgo.svc.cluster.local
db_username: postgres
db_password: changeme
primary_ip: 1.1.1.1
secondary_ip: 1.1.1.2
cluster_ip_start: 1.1.1.3
cluster_ip_end: 1.1.1.4
