---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}-api
  labels:
    app: {{ .Release.Name  }}-api
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name  }}-api
  replicas: {{ .Values.api.replicas }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name  }}-api
    spec:
      securityContext:
        runAsUser: {{ .Values.userid }}
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 2
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 2
      terminationGracePeriodSeconds: 5
      affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - {{ .Release.Name  }}-api
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: primary-api
          image: {{ .Values.api.image }}
          imagePullPolicy: {{ .Values.api.imagePullPolicy }}
          ports:
            - containerPort: 4080
            - containerPort: 4000
            - containerPort: 3022
          resources:
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "1024Mi"
              cpu: {{ .Values.api.cpus }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: 4080
            initialDelaySeconds: 15
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: 4080
            initialDelaySeconds: 3
            periodSeconds: 3
          env:
            - name: EXTERNAL_IP
              value: {{ .Values.hostname }}
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: {{ .Values.db_secret }}, key: user} }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: {{ .Values.db_secret }}, key: password } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: {{ .Values.db_secret }}, key: dbname } }
            - name: DB_HOSTNAME
              valueFrom: { secretKeyRef: { name: {{ .Values.db_secret }}, key: host} }
            - name: DB_PORT
              value: {{ quote .Values.db_port }}
            - name: DB_SSL_ENABLED
              value: {{ quote .Values.db_ssl_enabled }}
            - name: CDR_ROOT_PATH
              value: {{ .Values.cdr_root_path }}
            - name: LOGGING_LEVEL
              value: {{ .Values.api.logging_level }}
            - name: TRACEROUTE_SERVICE
              value: {{ .Release.Name  }}-traceroute-service
            - name: LOCAL_NATS
              value: {{ .Release.Name  }}-nats
            - name: ADMIN_NODE
              value: "FALSE"
            - name: WORKER_NODE
              value: "TRUE"
            - name: CERT_KEY
              value: /home/app/cert/appliance_key.pem
            - name: CERT_PUBLIC
              value: /home/app/cert/appliance.pem
