---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name  }}-traceroute-service
  labels:
    app: {{ .Release.Name  }}-traceroute-service
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name  }}-traceroute-service
  replicas: {{ .Values.traceroute.replicas }}  # Update this line to use the replicas value from values.yaml
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 70%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Release.Name  }}-traceroute-service
    spec:
      securityContext:
        # allowPrivilegeEscalation: false
        # privileged: true
        runAsUser: 0
        # capabilities:
          # add: ["CAP_NET_RAW"]
      tolerations:
        - effect: NoExecute
          key: node.kubernetes.io/unreachable
          operator: Exists
          tolerationSeconds: 2
        - effect: NoExecute
          key: node.kubernetes.io/not-ready
          operator: Exists
          tolerationSeconds: 2
      terminationGracePeriodSeconds: 5
      # affinity:
      #     podAntiAffinity:
      #       preferredDuringSchedulingIgnoredDuringExecution:
      #       - weight: 100
      #         podAffinityTerm:
      #           labelSelector:
      #             matchExpressions:
      #             - key: app
      #               operator: In
      #               values:
      #               - {{ .Release.Name  }}-primary-web
      #               - {{ .Release.Name  }}-secondary-web
      #           topologyKey: "kubernetes.io/hostname"
      containers:
        - name: {{ .Release.Name  }}-traceroute
          image: {{ .Values.traceroute.image }}
          imagePullPolicy: {{ .Values.traceroute.imagePullPolicy }}
          ports:
            - containerPort: 4100
          resources:
            requests:
              # memory: "512Mi"
              cpu: "256m"
            limits:
              # memory: "1024Mi"
              cpu: {{ .Values.traceroute.cpus }}
          env:
            - name: NATS_HOSTNAME
              value: {{ .Values.nats_server }}
