---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    app: {{ .Release.Name  }}-web
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-web     
  replicas: {{ .Values.web.replicas }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name  }}-web
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8080'
        prometheus.io/path: '/metrics'
    spec:
      containers:
        - name: web
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.web.pullPolicy }}
          ports:
            - containerPort: 8080
            - containerPort: 3022
          env:
            - name: HOST
              value: {{ .Values.hostname }}
            - name: INTERNAL_PORT
              value: "8080"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: secrets
                  key: secret_key_base
            - name: EXTERNAL_IP
              value: "your-server"
              # valueFrom:
              #     configMapKeyRef:
              #       name: {{ template "name" . }}-config
              #       key: EXTERNAL_IP
            - name: HTTPS_PORT
              value: "80"
            - name: DB_USER
              value: {{ .Values.global.postgresql.postgresqlUsername }}
            - name: DB_PASSWORD
              value: {{ .Values.global.postgresql.postgresqlPassword }} 
            # - name: DB_PASSWORD
            #   valueFrom:
            #     secretKeyRef:
            #       name: {{ .Release.Name }}-postgresql
            #       key: postgresql-password
            - name: DB_NAME
              value: {{ .Values.global.postgresql.postgresqlDatabase }}
            - name: DB_HOSTNAME
              value: {{ .Release.Name }}-postgresql.{{ .Release.Namespace }}.svc.cluster.local
            - name: LOGGING_LEVEL
              value: {{ .Values.logging_level }}
            - name: CDR_ROOT_PATH
              value: {{ .Values.cdr_root_path }} 