apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secondary-api-external
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-secondary-api
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if eq .Values.loadBalancerType "onprem" }}
    metallb.universe.tf/address-pool: {{ .Values.environment }}-secondary-ip
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx-ingress-controller
  ports:
    - port: {{ .Values.networking.api_port }}
      targetPort: 80
      protocol: TCP
      name: web
    - port: 443
      targetPort: 443
      protocol: TCP
      name: https
