apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-echo-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: echo-server
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP
