apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name  }}-admin-service
  labels:
    app: {{ .Release.Name }}-admin-service
  # annotations:
    # metallb.universe.tf/address-pool: secondary-pool
spec:
  type: ClusterIP
  # externalTrafficPolicy: Local
  selector:
    app: {{ .Release.Name  }}-admin-service
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: web
    - port: 22
      targetPort: 3022
      protocol: TCP
      name: sftp