apiVersion: v1
kind: ConfigMap
metadata:
  # namespace: metallb-system
  name: metallb-config
data:
  config: |
    address-pools:
    - name: primary-pool
      protocol: layer2
      addresses:
      - {{ .Values.primary_ip }}/32
    - name: secondary-pool
      protocol: layer2
      addresses:
      - {{ .Values.secondary_ip }}/32
    - name: default
      protocol: layer2
      addresses:
      - {{ .Values.cluster_ip_start }}/32