---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  db_user: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_username | quote }}{{ end }}
  db_password: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_password | quote }}{{ end }}
  db_name: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_name | quote }}{{ end }}
  db_hostname: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_hostname | quote }}{{ end }}
  db_port: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_port | quote }}{{ end }}
  db_ssl_enabled: {{ if .Values.db.useSecret }}{{ .Values.db.secretName | quote }}{{ else }}{{ .Values.db.values.db_ssl_enabled | quote }}{{ end }}
