# apiVersion: v1
# kind: Service
# metadata:
#   name: grafana
#   labels:
#     app: grafana
# spec:
#   type: LoadBalancer
#   selector:
#     app.kubernetes.io/name: grafana
#   ports:
#     - port: 82
#       targetPort: 3000
#       protocol: TCP
#       name: http
