# ---
# apiVersion: traefik.io/v1alpha1
# kind: IngressRoute
# metadata:
#   name: {{ .Release.Name }}-vue-app-route
# spec:
#   entryPoints:
#     - web  # For HTTP traffic (port 80)
#   routes:
#     - match: Path(`/`) || PathPrefix(`/#`)
#       kind: Rule
#       services:
#         - name: {{ .Release.Name }}-service
#           port: {{ .Values.vue_web.port }}
