{{- if .Values.secondary_api.createLoadBalancer }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-secondary-api-external
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}-secondary-api
  annotations:
    kubernetes.io/ingress.class: nginx
    {{- if .Values.secondary_api.advertiseL2MetalLb }}
    metallb.universe.tf/address-pool: secondary-ip
    {{- end }}
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx-ingress-controller
  ports:
    - port: {{ .Values.secondary_api.port }}
      targetPort: 80
      protocol: TCP
      name: web
    - port: {{ .Values.secondary_api.https_port }}
      targetPort: 443
      protocol: TCP
      name: https
{{- end }}
