apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name  }}-admin-web
  labels:
    app: {{ .Release.Name }}-admin-web
  annotations:
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/affinity: "true"
    traefik.ingress.kubernetes.io/session-cookie-name: "sticky"
    metallb.universe.tf/address-pool: secondary-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: {{ .Release.Name  }}-web
  ports:
    - port: 80
      targetPort: 4000
      protocol: TCP
      name: web
    - port: 22
      targetPort: 3022
      protocol: TCP
      name: sftp