# ---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: ct-ingress
#   annotations:
#     ingress.kubernetes.io/rewrite-target: /
#     kubernetes.io/ingress.class: traefik
# spec:
#   rules:
#   - http:
#       paths:
#         - path: /
#           backend:
#             serviceName: {{ template "name" . }}-service
#             servicePort: 8080